#!/bin/zsh

while IFS=, read -r id species abbrev fname fabb <&3; do {
    query="\"$species\"[Title/Abstract] AND Journal Article[PT]"
    esearch -db pubmed -query $query | efetch -format uid | sed '/^$/d' > pmids/$fname
    query="\"$species\"[Title/Abstract] OR \"$abbrev\"[Title/Abstract] AND Journal Article[PT]"
    esearch -db pubmed -query $query | efetch -format uid | sed '/^$/d' > pmids/$fabb
    resfull=$(wc -l < "pmids/$fname" | xargs)
    resabb=$(wc -l < "pmids/$fabb" | xargs)
    echo "$id,$species,$abbrev,$fname,$fabb,$resfull,$resabb"
} done 3< species_20k.csv
